### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by iversond** [UMN-PeopleSoft/psoftjmx#1]
We had `psoftbeat` running for a week with most domains up, but a few where up and down during that time. At one point, the entire beat stopped responding. In the `psoftjmx.log` file we saw this error:

```
lvl=eror msg="JMX Request: RunJMXCommand Error response for APPDOM:  error: dial unix /tmp/psmetric.socket: connect: connection refused" module=psoftjmx
```
Simply restarting the beat resolved the connection issue, but wanted to log this issue in case it's indicative of a bug.

**Comment by NateWerner** [comment]
I think the problem is with the socket file being in /tmp,  this folder can be cleaned automatically.  Will move to running folder so it's more self contained.

**Comment by NateWerner** [comment]
Moved the nailgun socket to the <beats/run> folder.
